name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code
    
    - name: Build the C# code       # Name of step
      run: dotnew build # Command to run

    - name: Run the c#tests
      working-directory: cd "C:\Users\gmadan\OneDrive - American International Group, Inc\Documents\GitHub\DevOps-Unit-5-Workshop\DotnetTemplate.Web.Tests"  
      run: dotnet test